#
# Copyright (C) 2016 Wind River Systems, Inc.
#

TARGET_SUPPORTED_KTYPES_xilinx-zynqmp = "standard preempt-rt cgl"

KBRANCH_DEFAULT_standard_xilinx-zynqmp = "standard/xilinx/sdk-2017-03/xilinx-zynqmp"
KBRANCH_DEFAULT_preempt-rt_xilinx-zynqmp = "standard/preempt-rt/xilinx/sdk-2017-03/xilinx-zynqmp"
KBRANCH_DEFAULT_cgl_xilinx-zynqmp = "standard/cgl/xilinx/sdk-2017-03/xilinx-zynqmp"

KERNEL_DEVICETREE_xilinx-zynqmp = "xilinx/zynqmp-zcu102-rev1.0.dtb"
